// apps/web/src/pages/Account.tsx
import { useState } from 'react';
import { api, ApiError } from '../api';
import { useApi } from '../useApi';
import { useAuth } from '../auth';
import Select from '../components/Select';

type AccountData = {
	profile: { name: string; email: string; homeTz: string };
	timeZones: string[];
};

/**
 * Account settings: the profile the app greets you by, and the password you
 * sign in with. Two independent forms rather than one, because they fail for
 * unrelated reasons and a wrong current password should not discard a name
 * change typed at the same time. Each keeps its own message for that reason.
 */
export default function Account() {
	const { data, error, loading, reload } = useApi<AccountData>('/account');

	return (
		<main className="mx-auto flex w-full max-w-[34rem] flex-col gap-5 px-6 pt-10 pb-16">
			<header>
				<h1 className="text-[1.7rem]">Account settings</h1>
				<p className="muted mt-1">Manage how you sign in and how times are shown to you.</p>
			</header>

			{error && (
				<p role="alert" className="text-warn">
					{error}
				</p>
			)}
			{loading && !data && <p className="muted">Loading...</p>}

			{data && (
				<>
					{/* Keyed on the loaded values so a reload after a save reseeds the
					    fields instead of leaving the form showing what was typed. */}
					<Profile key={data.profile.email} data={data} onSaved={reload} />
					<Password />
				</>
			)}
		</main>
	);
}

function Profile({ data, onSaved }: { data: AccountData; onSaved: () => void }) {
	const { refresh } = useAuth();
	const [name, setName] = useState(data.profile.name);
	const [email, setEmail] = useState(data.profile.email);
	const [homeTz, setHomeTz] = useState(data.profile.homeTz);
	const [msg, setMsg] = useState<{ ok: boolean; text: string } | null>(null);
	const [saving, setSaving] = useState(false);

	const zones = data.timeZones.map((tz) => ({ value: tz, label: tz.replace(/_/g, ' ') }));

	async function submit(e: React.FormEvent) {
		e.preventDefault();
		setSaving(true);
		setMsg(null);
		try {
			await api('/account/profile', { method: 'PATCH', body: { name, email, homeTz } });
			setMsg({ ok: true, text: 'Profile saved.' });
			// The top bar renders the session user, not this form, so it has to be
			// told the name it is showing has changed.
			await refresh();
			onSaved();
		} catch (err) {
			setMsg({
				ok: false,
				text: err instanceof ApiError ? err.message : 'Could not save your profile.'
			});
		} finally {
			setSaving(false);
		}
	}

	return (
		<section className="card p-6">
			<h2 className="mb-4 text-[1.15rem]">Profile</h2>
			<Message msg={msg} />
			<form className="flex flex-col gap-3.5" onSubmit={submit}>
				<Field label="Name" type="text" autoComplete="name" value={name} onChange={setName} />
				<Field label="Email" type="email" autoComplete="email" value={email} onChange={setEmail} />
				<label className="flex flex-col gap-1.5 text-sm font-medium text-ink-soft">
					Home time zone
					<Select
						value={homeTz}
						onChange={setHomeTz}
						options={zones}
						ariaLabel="Home time zone"
					/>
				</label>
				<button className="btn primary mt-1 self-start" type="submit" disabled={saving}>
					{saving ? 'Saving...' : 'Save profile'}
				</button>
			</form>
		</section>
	);
}

function Password() {
	const [current, setCurrent] = useState('');
	const [next, setNext] = useState('');
	const [confirm, setConfirm] = useState('');
	const [msg, setMsg] = useState<{ ok: boolean; text: string } | null>(null);
	const [saving, setSaving] = useState(false);

	async function submit(e: React.FormEvent) {
		e.preventDefault();
		setSaving(true);
		setMsg(null);
		try {
			await api('/account/password', { method: 'POST', body: { current, next, confirm } });
			setMsg({ ok: true, text: 'Password updated.' });
			// Clearing on success matters more here than elsewhere: these are live
			// credentials sitting in a form the next person at the desk can read.
			setCurrent('');
			setNext('');
			setConfirm('');
		} catch (err) {
			setMsg({
				ok: false,
				text: err instanceof ApiError ? err.message : 'Could not change your password.'
			});
		} finally {
			setSaving(false);
		}
	}

	return (
		<section className="card p-6">
			<h2 className="mb-4 text-[1.15rem]">Password</h2>
			<Message msg={msg} />
			<form className="flex flex-col gap-3.5" onSubmit={submit}>
				<Field
					label="Current password"
					type="password"
					autoComplete="current-password"
					value={current}
					onChange={setCurrent}
				/>
				<Field
					label="New password"
					type="password"
					autoComplete="new-password"
					hint="At least 8 characters"
					value={next}
					onChange={setNext}
				/>
				<Field
					label="Confirm new password"
					type="password"
					autoComplete="new-password"
					value={confirm}
					onChange={setConfirm}
				/>
				<button className="btn primary mt-1 self-start" type="submit" disabled={saving}>
					{saving ? 'Working...' : 'Change password'}
				</button>
			</form>
		</section>
	);
}

/** Success is polite and failure is assertive, so a screen reader interrupts
 *  only for the one the user has to act on. */
function Message({ msg }: { msg: { ok: boolean; text: string } | null }) {
	if (!msg) return null;
	return (
		<p
			role={msg.ok ? 'status' : 'alert'}
			className={[
				'mb-4 rounded px-3 py-2 text-sm',
				msg.ok ? 'bg-accent-soft text-accent-ink' : 'bg-warn-soft text-warn'
			].join(' ')}
		>
			{msg.text}
		</p>
	);
}

function Field({
	label,
	hint,
	value,
	onChange,
	...input
}: {
	label: string;
	hint?: string;
	value: string;
	onChange: (v: string) => void;
} & Omit<React.InputHTMLAttributes<HTMLInputElement>, 'value' | 'onChange'>) {
	return (
		<label className="flex flex-col gap-1.5 text-sm font-medium text-ink-soft">
			{label}
			<input
				{...input}
				required
				value={value}
				onChange={(e) => onChange(e.target.value)}
				className="rounded border border-line bg-surface px-3 py-2.5 font-normal text-ink outline-none focus:border-accent"
			/>
			{/* A rule the value has to keep satisfying stays visible while typing;
			    a placeholder would be gone at the first keystroke. */}
			{hint && <span className="text-[0.78rem] font-normal text-ink-faint">{hint}</span>}
		</label>
	);
}

// apps/svelte/src/routes/account/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Select from '$lib/components/Select.svelte';
	let { data, form } = $props();

	const profileMsg = $derived(form?.section === 'profile' ? form : null);
	const passwordMsg = $derived(form?.section === 'password' ? form : null);

	let homeTz = $state(data.profile.homeTz);
	const tzOptions = data.timeZones.map((tz: string) => ({ value: tz, label: tz.replace('_', ' ') }));
</script>

<div class="accwrap">
	<header class="acchead">
		<h1>Account settings</h1>
		<p class="muted">Manage how you sign in and how times are shown to you.</p>
	</header>

	<section class="card block">
		<h2>Profile</h2>
		{#if profileMsg?.error}<p class="err">{profileMsg.error}</p>{/if}
		{#if profileMsg?.ok}<p class="ok">Profile saved.</p>{/if}
		<form method="POST" action="?/profile" use:enhance>
			<label>Name<input name="name" type="text" value={data.profile.name} required /></label>
			<label>Email<input name="email" type="email" value={data.profile.email} required /></label>
			<label>
				Home time zone
				<Select name="homeTz" bind:value={homeTz} options={tzOptions} ariaLabel="Home time zone" />
			</label>
			<button class="btn primary" type="submit">Save profile</button>
		</form>
	</section>

	<section class="card block">
		<h2>Password</h2>
		{#if passwordMsg?.error}<p class="err">{passwordMsg.error}</p>{/if}
		{#if passwordMsg?.ok}<p class="ok">Password updated.</p>{/if}
		<form method="POST" action="?/password" use:enhance={() => async ({ update }) => update({ reset: true })}>
			<label>Current password<input name="current" type="password" required /></label>
			<label
				>New password<input name="next" type="password" required />
				<span class="hint muted">At least 8 characters</span></label
			>
			<label>Confirm new password<input name="confirm" type="password" required /></label>
			<button class="btn primary" type="submit">Change password</button>
		</form>
	</section>
</div>

<style>
	.accwrap {
		max-width: 34rem;
		margin: 0 auto;
		padding: 2.5rem 1.5rem 4rem;
		display: flex;
		flex-direction: column;
		gap: 1.2rem;
	}
	.acchead h1 {
		font-size: 1.7rem;
	}
	.acchead p {
		margin: 0.3rem 0 0;
	}
	.block {
		padding: 1.5rem 1.6rem;
	}
	.block h2 {
		font-size: 1.15rem;
		margin: 0 0 1rem;
	}
	form {
		display: flex;
		flex-direction: column;
		gap: 0.9rem;
	}
	label {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
		font-size: 0.85rem;
		font-weight: 500;
		color: var(--ink-soft);
	}
	input {
		padding: 0.6rem 0.75rem;
		border: 1px solid var(--line);
		border-radius: var(--r);
		font: inherit;
		background: var(--surface);
		color: var(--ink);
	}
	input:focus {
		outline: none;
		border-color: var(--accent);
	}
	/* Rules the field must satisfy stay visible while typing; a placeholder would
	   vanish at the first keystroke. */
	.hint {
		font-size: 0.78rem;
		font-weight: 400;
	}
	button {
		align-self: flex-start;
		margin-top: 0.3rem;
	}
	.err {
		background: var(--warn-soft);
		color: var(--warn);
		font-size: 0.85rem;
		padding: 0.55rem 0.75rem;
		border-radius: var(--r);
		margin: 0 0 1rem;
	}
	.ok {
		background: var(--accent-soft);
		color: var(--accent-ink);
		font-size: 0.85rem;
		padding: 0.55rem 0.75rem;
		border-radius: var(--r);
		margin: 0 0 1rem;
	}
</style>
