// apps/web/src/pages/Trips.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router';
import { api, ApiError } from '../api';
import { useApi } from '../useApi';
import { Field } from '../components/Field';
import Cover from '../components/Cover';

type City = { id: string; name: string; photo: string | null };
type Trip = {
	id: string;
	name: string;
	dates: string;
	cover: string;
	role: string;
	cities: City[];
	memberCount: number;
};

export default function Trips() {
	const { data, error, loading, reload } = useApi<{ trips: Trip[] }>('/trips');
	const [showNew, setShowNew] = useState(false);

	return (
		<>
			<section className="container flex items-end justify-between pt-12 pb-6">
				<div>
					<h1 className="text-[2rem]">My trips</h1>
					<p className="muted">Trips you organize or belong to.</p>
				</div>
				<button className="btn primary" onClick={() => setShowNew((v) => !v)}>
					New trip
				</button>
			</section>

			{showNew && (
				<section className="container">
					<NewTrip onCancel={() => setShowNew(false)} onCreated={reload} />
				</section>
			)}

			<section className="container grid grid-cols-1 gap-5 md:grid-cols-2">
				{error && <p className="col-span-full text-warn">{error}</p>}

				{data?.trips.map((t) => (
					<TripCard key={t.id} trip={t} />
				))}

				{/* Only after a successful load, so an empty grid mid-fetch does not
				    briefly claim the user has no trips. */}
				{!loading && !error && data?.trips.length === 0 && (
					<p className="muted col-span-full py-8">
						No trips yet. Create your first one to get started.
					</p>
				)}
			</section>
		</>
	);
}

function TripCard({ trip }: { trip: Trip }) {
	const first = trip.cities[0] ?? null;
	return (
		<Link
			to={`/trips/${trip.id}`}
			className="card overflow-hidden transition-[box-shadow,transform] duration-150 hover:-translate-y-0.5 hover:shadow-card"
		>
			{/* The trip's own gradient stays the fallback, so a trip with no cities
			    yet, or one whose first city has no picture, looks the same as it
			    always did rather than blank. */}
			<Cover
				photo={first?.photo ?? null}
				seed={trip.name}
				height="150px"
				background={first?.photo ? undefined : trip.cover}
			>
				<span className="chip absolute top-4 left-4 border-none bg-white/85">
					{trip.cities.length} {trip.cities.length === 1 ? 'city' : 'cities'}
				</span>
			</Cover>
			<div className="px-6 pt-5 pb-6">
				<h3 className="text-[1.15rem]">{trip.name}</h3>
				<p className="muted mt-1 mb-3 text-[0.9rem]">{trip.dates}</p>
				<p className="mb-4 text-[0.95rem] text-ink-soft">
					{trip.cities.length ? trip.cities.map((c) => c.name).join('  ›  ') : 'No cities yet'}
				</p>
				<span className="flex flex-wrap items-center gap-2.5">
					<span className="chip accent capitalize">{trip.role}</span>
					<span className="muted text-[0.85rem]">
						{trip.memberCount} {trip.memberCount === 1 ? 'person' : 'people'}
					</span>
				</span>
			</div>
		</Link>
	);
}

function NewTrip({ onCancel, onCreated }: { onCancel: () => void; onCreated: () => void }) {
	const navigate = useNavigate();
	const [name, setName] = useState('');
	const [dates, setDates] = useState('');
	const [currency, setCurrency] = useState('USD');
	const [error, setError] = useState<string | null>(null);
	const [saving, setSaving] = useState(false);

	async function submit(e: React.FormEvent) {
		e.preventDefault();
		if (!name.trim()) {
			setError('Give your trip a name.');
			return;
		}
		setSaving(true);
		setError(null);
		try {
			const { trip } = await api<{ trip: { id: string } }>('/trips', {
				method: 'POST',
				body: {
					name,
					dates: dates.trim() || 'Dates to be set',
					homeCurrency: currency
				}
			});
			onCreated();
			navigate(`/trips/${trip.id}`);
		} catch (err) {
			setError(err instanceof ApiError ? err.message : 'Could not create the trip.');
			setSaving(false);
		}
	}

	return (
		<form className="card mb-6 p-6" onSubmit={submit}>
			{error && (
				<p role="alert" className="mb-3 text-[0.85rem] text-warn">
					{error}
				</p>
			)}
			<div className="grid grid-cols-1 gap-3.5 sm:grid-cols-[2fr_1.5fr_1fr]">
				<Field label="Trip name" value={name} onChange={(e) => setName(e.target.value)} />
				{/* The field takes free text, so the accepted shape has to stay
				    readable while you type it, which a placeholder does not. */}
				<Field
					label="Dates"
					value={dates}
					onChange={(e) => setDates(e.target.value)}
					hint="e.g. Jul 3 – Jul 15, 2027"
				/>
				<Field label="Currency" value={currency} onChange={(e) => setCurrency(e.target.value)} />
			</div>
			<div className="mt-4 flex justify-end gap-2.5">
				<button className="btn" type="button" onClick={onCancel}>
					Cancel
				</button>
				<button className="btn primary" type="submit" disabled={saving}>
					{saving ? 'Creating...' : 'Create trip'}
				</button>
			</div>
		</form>
	);
}

// apps/svelte/src/routes/trips/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	let { data, form } = $props();
	let showNew = $state(false);
</script>

<section class="container head">
	<div>
		<h1>My trips</h1>
		<p class="muted">Trips you organize or belong to.</p>
	</div>
	<button class="btn primary" onclick={() => (showNew = !showNew)}>New trip</button>
</section>

{#if showNew}
	<section class="container">
		<form class="card newtrip" method="POST" action="?/create" use:enhance>
			{#if form?.error}<p class="err">{form.error}</p>{/if}
			<div class="fields">
				<label>Trip name<input name="name" /></label>
				<label
					>Dates<input name="dates" />
					<span class="hint muted">e.g. Jul 3 – Jul 15, 2027</span></label
				>
				<label>Currency<input name="currency" value="USD" /></label>
			</div>
			<div class="acts">
				<button class="btn" type="button" onclick={() => (showNew = false)}>Cancel</button>
				<button class="btn primary" type="submit">Create trip</button>
			</div>
		</form>
	</section>
{/if}

<section class="container grid">
	{#each data.trips as t}
		<a class="card trip" href={`/trips/${t.id}`}>
			<div class="cover" style={`background:${t.cover}`}>
				<span class="chip">{t.cities.length} {t.cities.length === 1 ? 'city' : 'cities'}</span>
			</div>
			<div class="body">
				<h3>{t.name}</h3>
				<p class="muted dates">{t.dates}</p>
				<p class="route">
					{#if t.cities.length}
						{t.cities.map((c) => c.name).join('  ›  ')}
					{:else}
						No cities yet
					{/if}
				</p>
				<span class="chip accent role">{t.role}</span>
			</div>
		</a>
	{/each}

	{#if data.trips.length === 0}
		<p class="muted empty">No trips yet. Create your first one to get started.</p>
	{/if}
</section>

<style>
	.head {
		display: flex;
		align-items: flex-end;
		justify-content: space-between;
		padding: 3rem 1.5rem 1.5rem;
	}
	.head h1 {
		font-size: 2rem;
	}
	.newtrip {
		padding: 1.4rem;
		margin-bottom: 1.5rem;
	}
	.fields {
		display: grid;
		grid-template-columns: 2fr 1.5fr 1fr;
		gap: 0.9rem;
	}
	label {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
		font-size: 0.82rem;
		font-weight: 500;
		color: var(--ink-soft);
	}
	input {
		padding: 0.55rem 0.75rem;
		border: 1px solid var(--line);
		border-radius: var(--r);
		font: inherit;
		background: var(--surface);
	}
	input:focus {
		outline: none;
		border-color: var(--accent);
	}
	/* The field takes free text, so the accepted shape has to stay readable while
	   you type it, which a placeholder does not. */
	.hint {
		font-size: 0.75rem;
		font-weight: 400;
	}
	.acts {
		display: flex;
		justify-content: flex-end;
		gap: 0.6rem;
		margin-top: 1rem;
	}
	.err {
		color: var(--warn);
		font-size: 0.85rem;
		margin: 0 0 0.8rem;
	}
	.grid {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 1.25rem;
	}
	.trip {
		overflow: hidden;
		transition: box-shadow 0.15s ease, transform 0.1s ease;
	}
	.trip:hover {
		box-shadow: var(--shadow);
		transform: translateY(-2px);
	}
	.cover {
		height: 150px;
		display: flex;
		align-items: flex-start;
		padding: 1rem;
	}
	.cover .chip {
		background: rgba(255, 255, 255, 0.85);
		border: none;
	}
	.body {
		padding: 1.25rem 1.4rem 1.4rem;
	}
	.dates {
		font-size: 0.9rem;
		margin: 0.2rem 0 0.7rem;
	}
	.route {
		font-size: 0.95rem;
		color: var(--ink-soft);
		margin: 0 0 1rem;
	}
	.role {
		text-transform: capitalize;
	}
	.empty {
		grid-column: 1 / -1;
		padding: 2rem 0;
	}
	@media (max-width: 760px) {
		.grid {
			grid-template-columns: 1fr;
		}
		.fields {
			grid-template-columns: 1fr;
		}
	}
</style>
