// apps/web/src/pages/Pretrip.tsx
import { useState } from 'react';
import { api } from '../api';
import { useApi } from '../useApi';
import { useLiveSection } from '../useTripEvents';
import { useMutation } from '../useMutation';
import { formatMoney } from '../format';
import { useTrip } from './TripShell';
import Modal from '../components/Modal';
import Select from '../components/Select';
import SectionNav from '../components/SectionNav';
import FormError from '../components/FormError';
import EmptyState from '../components/EmptyState';
import ConfirmDialog from '../components/ConfirmDialog';
import { IconButton, LinkButton } from '../components/buttons';

type Person = { id: string; name: string; done: boolean };
type Task = {
	id: string;
	label: string;
	flag: string | null;
	people: Person[];
	shared: boolean;
	done: boolean;
	doneCount: number;
};
type CostItem = {
	id: string;
	label: string;
	category: string;
	cityId: string | null;
	cityName: string | null;
	amountCents: number;
};
type Data = {
	me: string;
	members: { id: string; name: string }[];
	tasks: Task[];
	packing: Task[];
	currency: string;
	memberCount: number;
	categories: string[];
	cities: { id: string; name: string }[];
	budget: {
		items: CostItem[];
		categoryTotals: Record<string, number>;
		grandTotal: number;
	};
};

type Draft = {
	id: string | null;
	label: string;
	amount: string;
	category: string;
	cityId: string;
};

const cap = (s: string) => s[0].toUpperCase() + s.slice(1);

export default function Pretrip() {
	const { trip } = useTrip();
	const { data, error, reload } = useApi<Data>(`/trips/${trip.id}/pretrip`);
	// One payload holds the tasks, the packing list and the cost estimates, and
	// the per-person figure depends on the roster.
	useLiveSection(['tasks', 'costs', 'members', 'trip'], reload);
	const [section, setSection] = useState('tasks');
	const [adding, setAdding] = useState<'task' | 'packing' | null>(null);
	/** Add and edit share one modal; `id` is null when adding. */
	const [editing, setEditing] = useState<Draft | null>(null);
	/** The row a confirmation is open for, and which list it came from. */
	const [pendingTask, setPendingTask] = useState<{ kind: 'task' | 'packing'; task: Task } | null>(
		null
	);
	const [pendingCost, setPendingCost] = useState<CostItem | null>(null);

	// One state machine for the small in-place writes this page makes (ticking a
	// box, and the deletes the dialogs below confirm), so a refusal lands in the
	// banner instead of being thrown into nothing.
	const act = useMutation<[() => Promise<unknown>]>((fn) => fn(), {
		onSuccess: reload,
		fallback: 'Could not save that.'
	});

	if (!data) return error ? <FormError message={error} variant="banner" /> : null;

	const doneCount = data.tasks.filter((t) => t.done).length;
	const packedCount = data.packing.filter((t) => t.done).length;

	/** Badges count what is still outstanding: the number you act on. */
	const sections = [
		{
			id: 'tasks',
			label: 'Tasks',
			badge: data.tasks.length - doneCount || null
		},
		{
			id: 'packing',
			label: 'Packing',
			badge: data.packing.length - packedCount || null
		},
		{ id: 'costs', label: 'Estimated costs', badge: null }
	];

	// Whole units: these are estimates, and the cents on a guessed number are
	// noise. The rounding is the formatter's, not a second division here.
	const fmt = (cents: number) => formatMoney(cents, data.currency, { whole: true });

	const grand = data.budget.grandTotal;
	const perPerson = data.memberCount ? grand / data.memberCount : grand;

	return (
		<div className="grid grid-cols-1 items-start gap-6 lg:grid-cols-[190px_minmax(0,1fr)]">
			<SectionNav
				items={sections}
				value={section}
				onChange={setSection}
				ariaLabel="Preparation sections"
			/>

			<div className="min-w-0">
				<FormError message={act.error} variant="banner" />

				{/* The row keeps its height across sections, so switching never shifts
				    the card below it up or down. */}
				<div className="mb-4 flex min-h-phead flex-wrap items-center justify-end gap-4">
					{section === 'tasks' && (
						<button className="btn primary" onClick={() => setAdding('task')}>
							+ Add task
						</button>
					)}
					{section === 'packing' && (
						<button className="btn primary" onClick={() => setAdding('packing')}>
							+ Add item
						</button>
					)}
					{section === 'costs' && (
						<button
							className="btn primary"
							onClick={() =>
								setEditing({
									id: null,
									label: '',
									amount: '',
									category: data.categories[0] ?? '',
									cityId: ''
								})
							}
						>
							+ Add cost
						</button>
					)}
				</div>

				{section !== 'costs' ? (
					<div className="card min-w-0 px-5 py-5">
						<TaskList
							items={section === 'tasks' ? data.tasks : data.packing}
							kind={section === 'tasks' ? 'task' : 'packing'}
							me={data.me}
							empty={section === 'tasks' ? 'No tasks yet.' : 'No packing items yet.'}
							onToggle={(taskId, userId) =>
								void act.run(() =>
									api(`/trips/${trip.id}/pretrip/tasks/${taskId}/toggle`, {
										method: 'POST',
										body: userId ? { userId } : {}
									})
								)
							}
							onRemove={(task) =>
								setPendingTask({
									kind: section === 'tasks' ? 'task' : 'packing',
									task
								})
							}
							onAdd={() => setAdding(section === 'tasks' ? 'task' : 'packing')}
						/>
					</div>
				) : (
					<>
						<div className="mb-4 flex min-w-0 flex-wrap items-end gap-6">
							<Stat label="Trip total" value={fmt(grand)} />
							<Stat label="Per person" value={fmt(perPerson)} />
						</div>

						<div className="mb-4 flex flex-wrap gap-2.5">
							{data.categories.map((c) => (
								<div
									key={c}
									className="flex min-w-0 items-baseline gap-1.5 rounded-full border border-line bg-surface px-3 py-1.5"
								>
									<span className="muted text-[0.78rem]">{cap(c)}</span>
									<strong className="text-[0.9rem]">
										{fmt(data.budget.categoryTotals[c] ?? 0)}
									</strong>
								</div>
							))}
						</div>

						<CostTable
							items={data.budget.items}
							total={grand}
							fmt={fmt}
							onEdit={(it) =>
								setEditing({
									id: it.id,
									label: it.label,
									amount: String(it.amountCents / 100),
									category: it.category,
									cityId: it.cityId ?? ''
								})
							}
							onRemove={(it) => setPendingCost(it)}
						/>
					</>
				)}
			</div>

			{adding && (
				<AddTask
					kind={adding}
					members={data.members}
					me={data.me}
					tripId={trip.id}
					onClose={() => setAdding(null)}
					onSaved={reload}
				/>
			)}

			{editing && (
				<EditCost
					draft={editing}
					currency={data.currency}
					categories={data.categories}
					cities={data.cities}
					tripId={trip.id}
					onClose={() => setEditing(null)}
					onSaved={reload}
				/>
			)}

			{/* Deleting a task takes the whole row, including everyone else's ticks
			    on it, which is the part that is not obvious from the row itself. */}
			<ConfirmDialog
				open={!!pendingTask}
				title={pendingTask?.kind === 'packing' ? 'Delete this packing item?' : 'Delete this task?'}
				busyLabel="Deleting..."
				body={pendingTask && <DeleteTaskBody task={pendingTask.task} />}
				onCancel={() => setPendingTask(null)}
				onConfirm={async () => {
					if (!pendingTask) return;
					await api(`/trips/${trip.id}/pretrip/tasks/${pendingTask.task.id}`, {
						method: 'DELETE'
					});
					setPendingTask(null);
					reload();
				}}
			/>

			<ConfirmDialog
				open={!!pendingCost}
				title="Delete this estimate?"
				busyLabel="Deleting..."
				body={
					pendingCost && (
						<>
							<p className="m-0 mb-2 font-semibold [overflow-wrap:anywhere]">{pendingCost.label}</p>
							<p className="m-0 text-[0.9rem]">
								{fmt(pendingCost.amountCents)} under {cap(pendingCost.category)}
								{pendingCost.cityName ? ` in ${pendingCost.cityName}` : ''}. The trip total and the
								per-person figure drop by it. Logged expenses are not affected.
							</p>
						</>
					)
				}
				onCancel={() => setPendingCost(null)}
				onConfirm={async () => {
					if (!pendingCost) return;
					await api(`/trips/${trip.id}/pretrip/costs/${pendingCost.id}`, { method: 'DELETE' });
					setPendingCost(null);
					reload();
				}}
			/>
		</div>
	);
}

/** Who a task delete takes down with it, stated in terms of what is on the row. */
function DeleteTaskBody({ task }: { task: Task }) {
	return (
		<>
			<p className="m-0 mb-2 font-semibold [overflow-wrap:anywhere]">{task.label}</p>
			<p className="m-0 text-[0.9rem]">
				{task.people.length > 0
					? `Assigned to ${task.people.length} ${
							task.people.length === 1 ? 'person' : 'people'
						}, ${task.doneCount} of whom have ticked it off. The row and everyone's ticks go.`
					: 'The row goes, along with whether it was ticked off.'}
			</p>
		</>
	);
}

function Stat({ label, value }: { label: string; value: string }) {
	return (
		<div className="flex flex-col">
			<span className="muted text-[0.8rem]">{label}</span>
			<strong className="font-serif text-2xl">{value}</strong>
		</div>
	);
}

function TaskList({
	items,
	kind,
	me,
	empty,
	onToggle,
	onRemove,
	onAdd
}: {
	items: Task[];
	kind: 'task' | 'packing';
	me: string;
	empty: string;
	onToggle: (taskId: string, userId?: string) => void;
	onRemove: (task: Task) => void;
	onAdd: () => void;
}) {
	/** Which task's roster is expanded. Only one at a time, because these lists are long. */
	const [openRoster, setOpenRoster] = useState<string | null>(null);

	if (items.length === 0) {
		return (
			<EmptyState
				className="py-2"
				message={empty}
				hint={
					kind === 'task'
						? 'Add one and assign who has to do it.'
						: 'Add what everyone needs to bring.'
				}
				action={
					<button type="button" className="btn small" onClick={onAdd}>
						{kind === 'task' ? 'Add task' : 'Add item'}
					</button>
				}
			/>
		);
	}

	return (
		<ul className="m-0 flex list-none flex-col gap-0.5 p-0">
			{items.map((it) => {
				const mine = it.people.find((p) => p.id === me) ?? null;
				return (
					<li key={it.id}>
						{/* `group` so the delete button can stay hidden until the row is
						    hovered without a hover-only stylesheet rule. */}
						<div className="group flex min-w-0 items-center gap-2.5 rounded-[10px] px-1.5 py-2 text-[0.94rem] hover:bg-surface-2">
							{it.people.length === 0 ? (
								<Box
									on={it.shared}
									label={`${it.shared ? 'Mark not done' : 'Mark done'}: ${it.label}`}
									onClick={() => onToggle(it.id)}
								/>
							) : mine ? (
								<Box
									on={mine.done}
									label={`${mine.done ? 'Mark not done for you' : 'Mark done for you'}: ${it.label}`}
									onClick={() => onToggle(it.id)}
								/>
							) : (
								/* Not yours to tick, so it is not a control. It still has to show
								   whether the task got done, or the row reads as struck through
								   and unchecked at the same time. */
								<span
									title={
										it.done ? 'Done by the people it is assigned to' : 'Assigned to other people'
									}
									aria-label={`${it.label} is assigned to other people and is ${it.done ? 'done' : 'not done yet'}`}
									className={`grid size-[18px] flex-none place-items-center rounded-[5px] border border-dashed text-[0.72rem] ${
										it.done
											? 'border-accent bg-accent-soft text-accent-ink'
											: 'border-line bg-surface-2'
									}`}
								>
									{it.done ? '✓' : ''}
								</span>
							)}

							<span
								className={`min-w-0 flex-1 truncate ${it.done ? 'text-ink-faint line-through' : ''}`}
								title={it.label}
							>
								{it.label}
							</span>

							{it.flag && <span className="chip flex-none border-warn text-warn">{it.flag}</span>}

							{it.people.length > 0 && (
								<div className="flex min-w-0 flex-none items-center gap-1.5">
									{it.people.length === 1 ? (
										<span
											className="max-w-36 truncate text-[0.74rem] text-ink-soft"
											title={it.people[0].name}
										>
											{it.people[0].name}
										</span>
									) : (
										/* The bar carries the at-a-glance signal, the count is the
										   accessible text, and the whole thing expands the roster. */
										<button
											type="button"
											aria-expanded={openRoster === it.id}
											title="Who still has to do this"
											onClick={() => setOpenRoster((v) => (v === it.id ? null : it.id))}
											className="flex cursor-pointer items-center gap-1.5 rounded-full border border-line bg-surface py-0.5 pr-2 pl-1.5 text-[0.74rem] text-ink-soft hover:border-accent"
										>
											<span className="block h-1 w-[34px] flex-none overflow-hidden rounded-full bg-line">
												<span
													className="block h-full bg-accent"
													style={{
														width: `${(it.doneCount / it.people.length) * 100}%`
													}}
												/>
											</span>
											<span className="tabular-nums whitespace-nowrap">
												{it.doneCount}/{it.people.length}
											</span>
										</button>
									)}
									{mine && (
										<span
											className={`flex-none rounded-full px-2 py-0.5 text-[0.72rem] whitespace-nowrap ${
												mine.done ? 'bg-accent-soft text-accent-ink' : 'bg-surface-2 text-ink-faint'
											}`}
										>
											{mine.done ? 'You: done' : 'You: to do'}
										</span>
									)}
								</div>
							)}

							<IconButton
								label={`Remove ${kind}: ${it.label}`}
								danger
								className="flex-none opacity-0 group-hover:opacity-100 focus-visible:opacity-100"
								onClick={() => onRemove(it)}
							>
								×
							</IconButton>
						</div>

						{openRoster === it.id && (
							<ul className="flex list-none flex-row flex-wrap gap-1.5 pt-0.5 pr-1.5 pb-2.5 pl-8">
								{it.people.map((p) => {
									const isMe = p.id === me;
									const cls = [
										'inline-flex max-w-44 items-center gap-1.5 rounded-full border px-2 py-0.5 text-[0.76rem]',
										p.done
											? 'border-transparent bg-accent-soft text-accent-ink'
											: 'border-line bg-surface text-ink-soft',
										isMe ? 'cursor-pointer' : 'cursor-default'
									].join(' ');
									const inner = (
										<>
											<span
												className={`grid size-3 flex-none place-items-center rounded-[4px] border border-current text-[0.6rem] ${p.done ? '' : 'opacity-70'}`}
											>
												{p.done ? '✓' : ''}
											</span>
											<span className="min-w-0 truncate" title={p.name}>
												{p.name}
												{isMe ? ' (you)' : ''}
											</span>
										</>
									);
									return (
										<li key={p.id} className="min-w-0">
											{isMe ? (
												<button
													type="button"
													className={cls}
													onClick={() => onToggle(it.id)}
													aria-label={`${p.done ? 'Mark not done' : 'Mark done'} for you: ${it.label}`}
												>
													{inner}
												</button>
											) : (
												<span className={cls}>{inner}</span>
											)}
										</li>
									);
								})}
							</ul>
						)}
					</li>
				);
			})}
		</ul>
	);
}

function Box({ on, label, onClick }: { on: boolean; label: string; onClick: () => void }) {
	return (
		<button
			type="button"
			onClick={onClick}
			aria-label={label}
			className={`grid size-[18px] flex-none cursor-pointer place-items-center rounded-[5px] border p-0 text-[0.72rem] text-white ${
				on ? 'border-accent bg-accent' : 'border-line bg-surface'
			}`}
		>
			{on ? '✓' : ''}
		</button>
	);
}

function CostTable({
	items,
	total,
	fmt,
	onEdit,
	onRemove
}: {
	items: CostItem[];
	total: number;
	fmt: (cents: number) => string;
	onEdit: (it: CostItem) => void;
	onRemove: (it: CostItem) => void;
}) {
	const CELL = 'border-b border-line px-4 py-2.5 text-left text-[0.92rem]';
	const TH =
		'border-b border-line px-4 py-2.5 text-left text-[0.72rem] font-medium tracking-[0.06em] text-ink-faint uppercase';

	return (
		<div className="card overflow-hidden p-0">
			<table className="w-full table-fixed border-collapse">
				<thead>
					<tr>
						<th className={TH}>Item</th>
						<th className={`${TH} w-[22%]`}>Category</th>
						<th className={`${TH} w-[18%]`}>City</th>
						<th className={`${TH} w-[16%] text-right`}>Amount</th>
						<th className={`${TH} w-22`} />
					</tr>
				</thead>
				<tbody>
					{items.map((it) => (
						<tr key={it.id} className="hover:bg-surface-2">
							<td className={`${CELL} truncate`} title={it.label}>
								{it.label}
							</td>
							<td className={CELL}>
								<span className="chip text-[0.74rem]">{cap(it.category)}</span>
							</td>
							<td className={`${CELL} muted truncate`} title={it.cityName ?? 'General'}>
								{it.cityName ?? 'General'}
							</td>
							<td className={`${CELL} text-right font-semibold tabular-nums`}>
								{fmt(it.amountCents)}
							</td>
							<td className={`${CELL} text-right`}>
								<span className="inline-flex justify-end gap-1">
									<IconButton label={`Edit ${it.label}`} onClick={() => onEdit(it)}>
										✎
									</IconButton>
									<IconButton label={`Remove ${it.label}`} danger onClick={() => onRemove(it)}>
										✕
									</IconButton>
								</span>
							</td>
						</tr>
					))}
					{items.length === 0 && (
						<tr>
							<td colSpan={5} className={`${CELL} muted`}>
								No estimates yet. Add one above.
							</td>
						</tr>
					)}
				</tbody>
				<tfoot>
					<tr className="bg-surface-2 font-medium">
						<td colSpan={3} className="px-4 py-2.5 text-[0.92rem]">
							Total
						</td>
						<td className="px-4 py-2.5 text-right text-[0.92rem] font-semibold tabular-nums">
							{fmt(total)}
						</td>
						<td />
					</tr>
				</tfoot>
			</table>
		</div>
	);
}

function AddTask({
	kind,
	members,
	me,
	tripId,
	onClose,
	onSaved
}: {
	kind: 'task' | 'packing';
	members: { id: string; name: string }[];
	me: string;
	tripId: string;
	onClose: () => void;
	onSaved: () => void;
}) {
	const [label, setLabel] = useState('');
	const [assignees, setAssignees] = useState<Set<string>>(new Set());

	const save = useMutation(
		async () => {
			await api(`/trips/${tripId}/pretrip/tasks`, {
				method: 'POST',
				body: { kind, label, assignees: [...assignees] }
			});
			onSaved();
			onClose();
		},
		{ fallback: 'Could not add that.' }
	);

	return (
		<Modal
			open
			size="sm"
			title={kind === 'task' ? 'Add a task' : 'Add a packing item'}
			onClose={onClose}
		>
			<form className="mform" onSubmit={save.submit}>
				<div className="mbody flex flex-col gap-3">
					<label className="field">
						<span>What needs doing?</span>
						<input
							autoFocus
							required
							value={label}
							onChange={(e) => setLabel(e.target.value)}
							className="input w-full"
						/>
					</label>

					<fieldset className="m-0 min-w-0 rounded-[10px] border border-line px-3 py-3">
						<legend className="px-1 text-[0.8rem] text-ink-soft">Who has to do it?</legend>
						<p className="muted m-0 mb-2 text-[0.78rem] text-pretty">
							Pick more than one and each person ticks their own box. Leave it empty for a one-off
							the group only needs once.
						</p>
						<div className="grid max-h-48 grid-cols-[repeat(auto-fill,minmax(min(9rem,100%),1fr))] gap-0.5 overflow-y-auto overscroll-contain">
							{members.map((m) => (
								<label
									key={m.id}
									className="flex min-w-0 cursor-pointer items-center gap-2 rounded-sm px-1.5 py-1 text-[0.85rem] text-ink hover:bg-surface-2"
								>
									<input
										type="checkbox"
										checked={assignees.has(m.id)}
										onChange={() =>
											setAssignees((prev) => {
												const next = new Set(prev);
												if (next.has(m.id)) next.delete(m.id);
												else next.add(m.id);
												return next;
											})
										}
										className="flex-none accent-accent"
									/>
									<span className="min-w-0 truncate">
										{m.name}
										{m.id === me ? ' (you)' : ''}
									</span>
								</label>
							))}
							{members.length === 0 && <p className="muted text-[0.9rem]">No members yet.</p>}
						</div>
						{members.length > 2 && (
							<div className="flex gap-3 px-1 pt-2">
								<LinkButton onClick={() => setAssignees(new Set(members.map((m) => m.id)))}>
									Select everyone
								</LinkButton>
								<LinkButton onClick={() => setAssignees(new Set())}>Clear</LinkButton>
							</div>
						)}
					</fieldset>
				</div>

				<div className="mfoot">
					<FormError message={save.error} />
					<button className="btn" type="button" onClick={onClose}>
						Cancel
					</button>
					<button className="btn primary" type="submit" disabled={save.busy}>
						{save.busy ? 'Adding...' : 'Add'}
					</button>
				</div>
			</form>
		</Modal>
	);
}

function EditCost({
	draft,
	currency,
	categories,
	cities,
	tripId,
	onClose,
	onSaved
}: {
	draft: Draft;
	currency: string;
	categories: string[];
	cities: { id: string; name: string }[];
	tripId: string;
	onClose: () => void;
	onSaved: () => void;
}) {
	const [label, setLabel] = useState(draft.label);
	const [amount, setAmount] = useState(draft.amount);
	const [category, setCategory] = useState(draft.category);
	const [cityId, setCityId] = useState(draft.cityId);

	const save = useMutation(
		async () => {
			await api(
				draft.id ? `/trips/${tripId}/pretrip/costs/${draft.id}` : `/trips/${tripId}/pretrip/costs`,
				{
					method: draft.id ? 'PUT' : 'POST',
					body: { label, amount: Number(amount), category, cityId }
				}
			);
			onSaved();
			onClose();
		},
		{ fallback: 'Could not save that item.' }
	);

	return (
		<Modal open size="sm" title={draft.id ? 'Edit cost' : 'Add cost'} onClose={onClose}>
			<form className="mform" onSubmit={save.submit}>
				<div className="mbody flex flex-col gap-3">
					<label className="field">
						<span>What is it?</span>
						<input
							autoFocus
							required
							value={label}
							onChange={(e) => setLabel(e.target.value)}
							className="input w-full"
						/>
					</label>
					<div className="flex flex-wrap gap-2.5">
						<label className="field flex-[0_1_130px]">
							<span>Amount ({currency})</span>
							<input
								type="number"
								min="0"
								step="1"
								required
								value={amount}
								onChange={(e) => setAmount(e.target.value)}
								className="input w-full"
							/>
						</label>
						<label className="field flex-[1_1_130px]">
							<span>Category</span>
							<Select
								options={categories.map((c) => ({ value: c, label: cap(c) }))}
								value={category}
								onChange={setCategory}
								ariaLabel="Category"
							/>
						</label>
						<label className="field flex-[1_1_130px]">
							<span>City</span>
							<Select
								options={[
									{ value: '', label: 'All / general' },
									...cities.map((c) => ({ value: c.id, label: c.name }))
								]}
								value={cityId}
								onChange={setCityId}
								ariaLabel="City"
							/>
						</label>
					</div>
				</div>

				<div className="mfoot">
					<FormError message={save.error} />
					<button className="btn" type="button" onClick={onClose}>
						Cancel
					</button>
					<button className="btn primary" type="submit" disabled={save.busy}>
						{save.busy ? 'Saving...' : draft.id ? 'Save changes' : 'Add cost'}
					</button>
				</div>
			</form>
		</Modal>
	);
}

// apps/svelte/src/routes/trips/[tripId]/pretrip/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Select from '$lib/components/Select.svelte';
	import Modal from '$lib/components/Modal.svelte';
	import SectionNav from '$lib/components/SectionNav.svelte';
	import { focusOnMount } from '$lib/focus';
	import type { PageData, ActionData } from './$types';

	let { data, form }: { data: PageData; form: ActionData } = $props();

	type Task = PageData['tasks'][number];

	const doneCount = $derived(data.tasks.filter((t) => t.done).length);
	const packedCount = $derived(data.packing.filter((t) => t.done).length);

	let section = $state('tasks');
	/** Badges count what is still outstanding: the number you act on. */
	const sections = $derived([
		{ id: 'tasks', label: 'Tasks', badge: data.tasks.length - doneCount || null },
		{ id: 'packing', label: 'Packing', badge: data.packing.length - packedCount || null },
		{ id: 'costs', label: 'Estimated costs', badge: null }
	]);

	/** Which task's roster is expanded. Only one at a time, because these lists are long. */
	let openRoster = $state<string | null>(null);

	function myShare(t: Task) {
		return t.people.find((p) => p.id === data.me) ?? null;
	}

	interface CostItem {
		id: string;
		label: string;
		category: string;
		cityId: string | null;
		amountCents: number;
	}

	/** Add and edit share one modal; `id` is null when adding. */
	let editing = $state<{
		id: string | null;
		label: string;
		amount: string;
		category: string;
		cityId: string;
	} | null>(null);

	let adding = $state<'task' | 'packing' | null>(null);
	let wholistEl = $state<HTMLDivElement | null>(null);

	function setAllAssignees(on: boolean): void {
		wholistEl
			?.querySelectorAll<HTMLInputElement>('input[name="assignee"]')
			.forEach((el) => (el.checked = on));
	}

	const catOptions = $derived(
		data.categories.map((c: string) => ({
			value: c,
			label: c[0].toUpperCase() + c.slice(1)
		}))
	);
	const cityOptions = $derived([
		{ value: '', label: 'All / general' },
		...data.cities.map((c) => ({ value: c.id, label: c.name }))
	]);

	function beginAdd() {
		editing = { id: null, label: '', amount: '', category: data.categories[0] ?? '', cityId: '' };
	}
	function beginEdit(it: CostItem) {
		editing = {
			id: it.id,
			label: it.label,
			amount: String(it.amountCents / 100),
			category: it.category,
			cityId: it.cityId ?? ''
		};
	}

	function fmt(cents: number): string {
		return new Intl.NumberFormat(undefined, {
			style: 'currency',
			currency: data.currency,
			maximumFractionDigits: 0
		}).format(cents / 100);
	}
	const cap = (s: string) => s[0].toUpperCase() + s.slice(1);
	const grand = $derived(data.budget.grandTotal);
	const perPerson = $derived(data.memberCount ? grand / data.memberCount : grand);
</script>

{#snippet roster(t: Task)}
	{@const mine = myShare(t)}
	<div class="rosterrow">
		{#if t.people.length === 1}
			<span class="solo" title={t.people[0].name}>{t.people[0].name}</span>
		{:else}
			<button
				type="button"
				class="prog"
				aria-expanded={openRoster === t.id}
				onclick={() => (openRoster = openRoster === t.id ? null : t.id)}
				title="Who still has to do this"
			>
				<span class="bar"
					><span style={`width:${(t.doneCount / t.people.length) * 100}%`}></span></span
				>
				<span class="pcount">{t.doneCount}/{t.people.length}</span>
			</button>
		{/if}
		{#if mine}
			<span class="youtag" class:on={mine.done}>{mine.done ? 'You: done' : 'You: to do'}</span>
		{/if}
	</div>
{/snippet}

{#snippet taskList(items: Task[], kind: 'task' | 'packing', empty: string)}
	<ul>
		{#each items as it (it.id)}
			{@const mine = myShare(it)}
			<li class:done={it.done}>
				<div class="row">
					{#if it.people.length === 0}
						<form method="POST" action="?/toggle" use:enhance class="chk">
							<input type="hidden" name="id" value={it.id} />
							<button
								class="box"
								class:on={it.shared}
								type="submit"
								aria-label={`${it.shared ? 'Mark not done' : 'Mark done'}: ${it.label}`}
								>{it.shared ? '✓' : ''}</button
							>
						</form>
					{:else if mine}
						<form method="POST" action="?/toggle" use:enhance class="chk">
							<input type="hidden" name="id" value={it.id} />
							<button
								class="box"
								class:on={mine.done}
								type="submit"
								aria-label={`${mine.done ? 'Mark not done for you' : 'Mark done for you'}: ${it.label}`}
								>{mine.done ? '✓' : ''}</button
							>
						</form>
					{:else}
						<span
							class="box other"
							title="Assigned to other people"
							aria-label={`${it.label} is not assigned to you`}
						></span>
					{/if}

					<span class="lbl" title={it.label}>{it.label}</span>
					{#if it.flag}<span class="chip warn">{it.flag}</span>{/if}
					{#if it.people.length > 0}
						{@render roster(it)}
					{/if}

					<form method="POST" action="?/remove" use:enhance class="delf">
						<input type="hidden" name="id" value={it.id} />
						<button class="del" aria-label={`Remove ${kind}: ${it.label}`}>×</button>
					</form>
				</div>

				{#if openRoster === it.id}
					<ul class="people">
						{#each it.people as p (p.id)}
							<li class="person">
								{#if p.id === data.me}
									<form method="POST" action="?/toggle" use:enhance>
										<input type="hidden" name="id" value={it.id} />
										<button
											type="submit"
											class="pchip"
											class:on={p.done}
											aria-label={`${p.done ? 'Mark not done' : 'Mark done'} for you: ${it.label}`}
										>
											<span class="tick">{p.done ? '✓' : ''}</span>
											<span class="pname">{p.name} (you)</span>
										</button>
									</form>
								{:else}
									<span class="pchip static" class:on={p.done}>
										<span class="tick">{p.done ? '✓' : ''}</span>
										<span class="pname" title={p.name}>{p.name}</span>
									</span>
								{/if}
							</li>
						{/each}
					</ul>
				{/if}
			</li>
		{/each}
		{#if items.length === 0}
			<li class="muted empty">{empty}</li>
		{/if}
	</ul>
{/snippet}

<div class="layout">
	<SectionNav items={sections} bind:value={section} ariaLabel="Preparation sections" />

	<div class="panel">
		{#if form?.error}
			<p class="note error" role="alert">{form.error}</p>
		{/if}

		{#if section === 'tasks'}
			<div class="phead">
				<button type="button" class="btn primary" onclick={() => (adding = 'task')}
					>+ Add task</button
				>
			</div>
			<div class="card block">
				{@render taskList(data.tasks, 'task', 'No tasks yet.')}
			</div>
		{:else if section === 'packing'}
			<div class="phead">
				<button type="button" class="btn primary" onclick={() => (adding = 'packing')}
					>+ Add item</button
				>
			</div>
			<div class="card block">
				{@render taskList(data.packing, 'packing', 'Nothing packed yet.')}
			</div>
		{:else}
			<div class="phead">
				<button type="button" class="btn primary" onclick={beginAdd}>+ Add cost</button>
			</div>

			<div class="summary">
				<div class="stat">
					<span class="muted">Trip total</span>
					<strong>{fmt(grand)}</strong>
				</div>
				<div class="stat">
					<span class="muted">Per person</span>
					<strong>{fmt(perPerson)}</strong>
				</div>
			</div>

			<div class="cats">
				{#each data.categories as cat}
					<div class="catchip">
						<span class="muted">{cap(cat)}</span>
						<strong>{fmt(data.budget.categoryTotals[cat] ?? 0)}</strong>
					</div>
				{/each}
			</div>

			<div class="card table">
				<table>
					<thead>
						<tr>
							<th>Item</th>
							<th>Category</th>
							<th>City</th>
							<th class="r">Amount</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{#each data.budget.items as it (it.id)}
							<tr>
								<td class="cell" title={it.label}>{it.label}</td>
								<td><span class="pill">{cap(it.category)}</span></td>
								<td class="muted cell" title={it.cityName ?? 'General'}
									>{it.cityName ?? 'General'}</td
								>
								<td class="r strong">{fmt(it.amountCents)}</td>
								<td class="r acts">
									<button
										type="button"
										class="iconbtn"
										onclick={() => beginEdit(it)}
										aria-label={`Edit ${it.label}`}>✎</button
									>
									<form method="POST" action="?/removeCost" use:enhance style="display:inline">
										<input type="hidden" name="itemId" value={it.id} />
										<button type="submit" class="iconbtn" aria-label={`Remove ${it.label}`}
											>✕</button
										>
									</form>
								</td>
							</tr>
						{/each}
						{#if data.budget.items.length === 0}
							<tr
								><td colspan="5" class="muted">No costs yet. Add your first estimate above.</td></tr
							>
						{/if}
					</tbody>
					<tfoot>
						<tr>
							<td colspan="3">Total</td>
							<td class="r strong">{fmt(grand)}</td>
							<td></td>
						</tr>
					</tfoot>
				</table>
			</div>
		{/if}
	</div>
</div>

{#if adding}
	{@const kind = adding}
	<Modal
		open
		title={kind === 'task' ? 'Add a task' : 'Add a packing item'}
		size="sm"
		onclose={() => (adding = null)}
	>
		<form
			method="POST"
			action="?/add"
			class="mform"
			use:enhance={() =>
				async ({ update }) => {
					await update();
					adding = null;
				}}
		>
			<div class="mbody">
				<input type="hidden" name="kind" value={kind} />
				<label>
					<span>What needs doing?</span>
					<input
						name="label"
						placeholder={kind === 'task' ? 'Apply for a visa' : 'Power adapter'}
						required
						use:focusOnMount
					/>
				</label>
				<fieldset class="who">
					<legend>Who has to do it?</legend>
					<p class="hint muted">
						Pick more than one and each person ticks their own box, so the task isn't done until
						everyone is. Leave empty for a one-off the group only needs once.
					</p>
					<div class="wholist" bind:this={wholistEl}>
						{#each data.members as m (m.id)}
							<label class="wholine">
								<input type="checkbox" name="assignee" value={m.id} />
								<span class="pname">{m.name}{m.id === data.me ? ' (you)' : ''}</span>
							</label>
						{/each}
						{#if data.members.length === 0}<p class="muted empty">No members yet.</p>{/if}
					</div>
					{#if data.members.length > 2}
						<div class="wholistfoot">
							<button type="button" class="linkbtn" onclick={() => setAllAssignees(true)}
								>Select everyone</button
							>
							<button type="button" class="linkbtn" onclick={() => setAllAssignees(false)}
								>Clear</button
							>
						</div>
					{/if}
				</fieldset>
			</div>
			<div class="mfoot">
				<button type="button" class="btn" onclick={() => (adding = null)}>Cancel</button>
				<button type="submit" class="btn primary">Add</button>
			</div>
		</form>
	</Modal>
{/if}

{#if editing}
	{@const e = editing}
	<Modal
		open
		title={e.id ? 'Edit cost' : 'Add cost'}
		size="sm"
		onclose={() => (editing = null)}
	>
		<form
			method="POST"
			action={e.id ? '?/saveCost' : '?/addCost'}
			class="mform"
			use:enhance={() =>
				async ({ update }) => {
					await update();
					editing = null;
				}}
		>
			<div class="mbody">
				{#if e.id}<input type="hidden" name="itemId" value={e.id} />{/if}
				<label>
					<span>What is it?</span>
					<input
						name="label"
						bind:value={e.label}
						placeholder="Museum tickets"
						required
						use:focusOnMount
					/>
				</label>
				<div class="frow">
					<label class="amtf">
						<span>Amount ({data.currency})</span>
						<input
							name="amount"
							type="number"
							min="0"
							step="1"
							bind:value={e.amount}
							placeholder="0"
							required
						/>
					</label>
					<label class="grow">
						<span>Category</span>
						<Select name="category" bind:value={e.category} options={catOptions} ariaLabel="Category" />
					</label>
					<label class="grow">
						<span>City</span>
						<Select name="cityId" bind:value={e.cityId} options={cityOptions} ariaLabel="City" />
					</label>
				</div>
			</div>
			<div class="mfoot">
				<button type="button" class="btn" onclick={() => (editing = null)}>Cancel</button>
				<button type="submit" class="btn primary">{e.id ? 'Save changes' : 'Add cost'}</button>
			</div>
		</form>
	</Modal>
{/if}

<style>
	.layout {
		display: grid;
		grid-template-columns: 190px minmax(0, 1fr);
		gap: 1.6rem;
		align-items: start;
	}
	.panel {
		min-width: 0;
	}
	/* Only the action button lives here now, so it sits at the trailing edge;
	   the row still reserves --phead-h so switching section never moves the card
	   below it. */
	.phead {
		display: flex;
		justify-content: flex-end;
		align-items: center;
		gap: 1rem;
		flex-wrap: wrap;
		min-height: var(--phead-h);
		margin-bottom: 1rem;
	}
	.note {
		border-radius: var(--r-sm);
		padding: 0.6rem 0.85rem;
		font-size: 0.9rem;
		margin-bottom: 1rem;
	}
	.note.error {
		background: var(--danger-soft, #fdecea);
		color: var(--danger-ink, #a12b21);
	}
	.block {
		padding: 1.2rem 1.3rem;
		min-width: 0;
	}
	ul {
		list-style: none;
		margin: 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 0.2rem;
	}
	.row {
		display: flex;
		align-items: center;
		gap: 0.6rem;
		padding: 0.5rem 0.4rem;
		border-radius: var(--r);
		font-size: 0.94rem;
		min-width: 0;
	}
	.row:hover {
		background: var(--surface-2);
	}
	.empty {
		color: var(--ink-faint);
		font-size: 0.9rem;
		padding: 0.5rem 0.4rem;
	}
	.chk {
		display: flex;
		flex: 0 0 auto;
	}
	.box {
		width: 18px;
		height: 18px;
		border-radius: 5px;
		border: 1px solid var(--line);
		background: var(--surface);
		cursor: pointer;
		display: grid;
		place-items: center;
		font-size: 0.72rem;
		color: #fff;
		padding: 0;
		flex: 0 0 auto;
	}
	.box.on {
		background: var(--accent);
		border-color: var(--accent);
	}
	.box.other {
		cursor: default;
		border-style: dashed;
		background: var(--surface-2);
	}
	.lbl {
		flex: 1 1 auto;
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.chip.warn {
		flex: 0 0 auto;
	}
	.done .lbl {
		color: var(--ink-faint);
		text-decoration: line-through;
	}

	/* Per-person progress. The bar carries the at-a-glance signal; the count is
	   the accessible text, and the whole thing expands the roster. */
	.rosterrow {
		display: flex;
		align-items: center;
		gap: 0.4rem;
		flex: 0 0 auto;
		min-width: 0;
	}
	.solo {
		font-size: 0.74rem;
		color: var(--ink-soft);
		max-width: 9rem;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.prog {
		display: flex;
		align-items: center;
		gap: 0.4rem;
		border: 1px solid var(--line);
		background: var(--surface);
		border-radius: 999px;
		padding: 0.12rem 0.5rem 0.12rem 0.4rem;
		cursor: pointer;
		font: inherit;
		font-size: 0.74rem;
		color: var(--ink-soft);
	}
	.prog:hover {
		border-color: var(--accent);
	}
	.bar {
		display: block;
		width: 34px;
		height: 4px;
		border-radius: 999px;
		background: var(--line);
		overflow: hidden;
		flex: 0 0 auto;
	}
	.bar span {
		display: block;
		height: 100%;
		background: var(--accent);
	}
	.pcount {
		font-variant-numeric: tabular-nums;
		white-space: nowrap;
	}
	.youtag {
		font-size: 0.72rem;
		border-radius: 999px;
		padding: 0.1rem 0.5rem;
		background: var(--surface-2);
		color: var(--ink-faint);
		white-space: nowrap;
		flex: 0 0 auto;
	}
	.youtag.on {
		background: var(--accent-soft);
		color: var(--accent-ink);
	}

	.people {
		display: flex;
		flex-direction: row;
		flex-wrap: wrap;
		gap: 0.3rem;
		padding: 0.1rem 0.4rem 0.6rem 2rem;
	}
	.person {
		min-width: 0;
	}
	.pchip {
		display: inline-flex;
		align-items: center;
		gap: 0.35rem;
		font: inherit;
		font-size: 0.76rem;
		border: 1px solid var(--line);
		background: var(--surface);
		color: var(--ink-soft);
		border-radius: 999px;
		padding: 0.14rem 0.55rem;
		max-width: 11rem;
		cursor: pointer;
	}
	.pchip.static {
		cursor: default;
	}
	.pchip.on {
		background: var(--accent-soft);
		border-color: transparent;
		color: var(--accent-ink);
	}
	.pchip .tick {
		display: grid;
		place-items: center;
		width: 12px;
		height: 12px;
		border-radius: 4px;
		border: 1px solid currentColor;
		font-size: 0.6rem;
		flex: 0 0 auto;
		opacity: 0.7;
	}
	.pchip.on .tick {
		opacity: 1;
	}
	.pname {
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		min-width: 0;
	}

	.delf {
		flex: 0 0 auto;
	}
	.del {
		border: none;
		background: none;
		color: var(--ink-faint);
		font-size: 1.05rem;
		line-height: 1;
		cursor: pointer;
		padding: 0 0.2rem;
		opacity: 0;
	}
	.row:hover .del,
	.del:focus-visible {
		opacity: 1;
	}
	.del:hover {
		color: var(--danger, #b4462a);
	}

	/* Add-task modal */
	.mform :global(.mbody) {
		display: flex;
		flex-direction: column;
		gap: 0.8rem;
	}
	.mform label {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
		font-size: 0.8rem;
		color: var(--ink-soft);
		min-width: 0;
	}
	.mform input[name='label'],
	.mform input[type='number'] {
		padding: 0.5rem 0.6rem;
		border: 1px solid var(--line);
		border-radius: var(--r);
		font: inherit;
		background: var(--surface);
		color: var(--ink);
		min-width: 0;
		max-width: 100%;
	}
	.who {
		border: 1px solid var(--line);
		border-radius: var(--r);
		padding: 0.7rem 0.8rem;
		margin: 0;
		min-width: 0;
	}
	.who legend {
		font-size: 0.8rem;
		color: var(--ink-soft);
		padding: 0 0.3rem;
	}
	.hint {
		margin: 0 0 0.5rem;
		font-size: 0.78rem;
		text-wrap: pretty;
	}
	.wholist {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(min(9rem, 100%), 1fr));
		gap: 0.15rem;
		max-height: 12rem;
		overflow-y: auto;
		overscroll-behavior: contain;
	}
	.wholistfoot {
		display: flex;
		gap: 0.75rem;
		padding: 0.4rem 0.3rem 0;
	}
	.linkbtn {
		border: 0;
		background: none;
		padding: 0;
		font: inherit;
		font-size: 0.78rem;
		color: var(--accent);
		cursor: pointer;
		text-decoration: underline;
	}
	.mform .wholine {
		display: flex;
		flex-direction: row;
		align-items: center;
		gap: 0.45rem;
		font-size: 0.85rem;
		color: var(--ink);
		padding: 0.25rem 0.3rem;
		border-radius: var(--r-sm);
		cursor: pointer;
		min-width: 0;
	}
	.wholine:hover {
		background: var(--surface-2);
	}
	.frow {
		display: flex;
		gap: 0.6rem;
		flex-wrap: wrap;
	}
	.frow .grow {
		flex: 1 1 130px;
	}
	.frow .amtf {
		flex: 0 1 130px;
	}

	/* Estimated costs */
	.summary {
		display: flex;
		align-items: flex-end;
		gap: 1.5rem;
		flex-wrap: wrap;
		min-width: 0;
		margin-bottom: 1rem;
	}
	.stat {
		display: flex;
		flex-direction: column;
	}
	.stat span {
		font-size: 0.8rem;
	}
	.stat strong {
		font-family: var(--serif);
		font-size: 1.5rem;
	}
	.cats {
		display: flex;
		flex-wrap: wrap;
		gap: 0.6rem;
		margin-bottom: 1rem;
	}
	.catchip {
		display: flex;
		align-items: baseline;
		gap: 0.45rem;
		border: 1px solid var(--line);
		border-radius: 999px;
		padding: 0.3rem 0.8rem;
		background: var(--surface);
		min-width: 0;
	}
	.catchip span {
		font-size: 0.78rem;
	}
	.catchip strong {
		font-size: 0.9rem;
	}
	.table {
		padding: 0;
		overflow: hidden;
	}
	table {
		width: 100%;
		border-collapse: collapse;
		table-layout: fixed;
	}
	th,
	td {
		padding: 0.7rem 1rem;
		text-align: left;
		border-bottom: 1px solid var(--line);
		font-size: 0.92rem;
	}
	th {
		font-size: 0.72rem;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: var(--ink-faint);
		font-weight: 500;
	}
	th:nth-child(2),
	td:nth-child(2) {
		width: 22%;
	}
	th:nth-child(3),
	td:nth-child(3) {
		width: 18%;
	}
	th:nth-child(4),
	td:nth-child(4) {
		width: 16%;
	}
	th:last-child,
	td:last-child {
		width: 5.5rem;
	}
	tbody tr:hover {
		background: var(--surface-2);
	}
	tfoot td {
		border-bottom: none;
		font-weight: 500;
		background: var(--surface-2);
	}
	.cell {
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.r {
		text-align: right;
	}
	.strong {
		font-weight: 600;
		font-variant-numeric: tabular-nums;
	}
	.pill {
		font-size: 0.74rem;
		padding: 0.12rem 0.5rem;
		border-radius: 999px;
		background: var(--accent-soft);
		color: var(--accent-ink);
		display: inline-block;
		max-width: 100%;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.acts {
		white-space: nowrap;
	}
	.iconbtn {
		border: none;
		background: none;
		color: var(--ink-faint);
		cursor: pointer;
		padding: 0.15rem 0.3rem;
		font-size: 0.9rem;
		border-radius: var(--r-sm);
	}
	.iconbtn:hover {
		color: var(--ink);
		background: var(--surface);
	}

	@media (max-width: 860px) {
		.layout {
			grid-template-columns: minmax(0, 1fr);
			gap: 0;
		}
	}
</style>
