// apps/svelte/src/routes/trips/[tripId]/people/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { PageData, ActionData } from './$types';

	let { data, form }: { data: PageData; form: ActionData } = $props();

	const members = $derived(data.people);
</script>

<div class="head">
	<p class="muted">Who's coming, and who still needs an invite.</p>
</div>

{#if form?.error}
	<p class="note error">{form.error}</p>
{:else if form?.ok && form?.message}
	<p class="note ok">{form.message}</p>
{/if}

<div class="grid" class:solo={!data.organizer}>
	<section class="card">
		<h3>Members</h3>
		<ul class="people">
			{#each members as p}
				<li>
					<span class="avatar">{p.name[0]}</span>
					<span class="who">
						<span class="name">
							<span class="nametext" title={p.name}>{p.name}</span>
							{#if p.id === data.me}<span class="tag you">you</span>{/if}
							{#if p.role === 'organizer'}<span class="tag org">organizer</span>{/if}
							{#if p.placeholder}<span class="tag invited">invited</span>
							{:else if p.seeded}<span class="tag seed">sample</span>{/if}
						</span>
						<span class="email muted"
							>{p.placeholder
								? `${p.email} (not joined yet)`
								: p.seeded
									? 'Sample companion'
									: p.email}</span
						>
					</span>
					{#if data.organizer && p.role !== 'organizer'}
						<form method="POST" action="?/remove" use:enhance>
							<input type="hidden" name="userId" value={p.id} />
							<button class="link-btn" type="submit" aria-label={`Remove ${p.name}`}>Remove</button>
						</form>
					{/if}
				</li>
			{/each}
		</ul>
	</section>

	{#if data.organizer}
		<section class="card invitecard">
			<h3>Invite someone</h3>
			<form method="POST" action="?/invite" class="invite-form" use:enhance>
				<input
					type="email"
					name="email"
					placeholder="name@example.com"
					required
					autocomplete="off"
				/>
				<button class="btn primary" type="submit">Send invite</button>
			</form>
			<p class="hint muted">
				If they already have an account they join right away. Otherwise they appear as a placeholder
				and take over the spot (and any expenses assigned to them) when they register with this
				email.
			</p>
		</section>
	{/if}
</div>

<style>
	.head {
		margin-bottom: 1.2rem;
	}
	.head .muted {
		margin: 0;
	}
	.note {
		border-radius: 8px;
		padding: 0.6rem 0.85rem;
		font-size: 0.9rem;
		margin-bottom: 1rem;
	}
	.note.error {
		background: var(--danger-soft, #fdecea);
		color: var(--danger-ink, #a12b21);
	}
	.note.ok {
		background: var(--accent-soft);
		color: var(--accent-ink);
	}
	/* Members takes the space it needs; Invite sits beside it at a fixed width and
	   drops underneath once there isn't room for both. */
	.grid {
		display: grid;
		grid-template-columns: minmax(0, 1fr) 340px;
		gap: 1.2rem;
		align-items: start;
	}
	@media (max-width: 900px) {
		.grid {
			grid-template-columns: minmax(0, 1fr);
		}
	}
	/* No invite card to sit beside, so don't leave a hole where it would be. */
	.grid.solo {
		grid-template-columns: minmax(0, 1fr);
	}
	.invitecard {
		position: sticky;
		top: 1rem;
	}
	.card {
		background: var(--surface);
		border: 1px solid var(--line);
		border-radius: 12px;
		padding: 1.2rem 1.3rem;
	}
	.card h3 {
		font-size: 1.05rem;
		margin-bottom: 0.9rem;
	}
	.people {
		list-style: none;
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
		gap: 0.15rem 1.4rem;
		padding: 0;
		margin: 0;
	}
	/* Row separators can't work here: with an auto-fill grid the last item of each
	   column isn't :last-child, so one column keeps a dangling line. Hover
	   highlighting is column-count independent and matches the expense picker. */
	.people li {
		display: flex;
		align-items: center;
		gap: 0.7rem;
		padding: 0.5rem 0.5rem;
		border-radius: var(--r-sm);
	}
	.people li:hover {
		background: var(--surface-2);
	}
	.avatar {
		width: 34px;
		height: 34px;
		border-radius: 999px;
		display: grid;
		place-items: center;
		background: var(--accent-soft);
		color: var(--accent-ink);
		font-weight: 600;
		flex-shrink: 0;
	}
	.who {
		display: flex;
		flex-direction: column;
		min-width: 0;
		flex: 1;
	}
	.name {
		font-weight: 500;
		display: flex;
		align-items: center;
		gap: 0.4rem;
		min-width: 0;
	}
	.nametext {
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.name .tag {
		flex: 0 0 auto;
	}
	.email {
		font-size: 0.82rem;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}
	.tag {
		font-size: 0.68rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.03em;
		padding: 0.08rem 0.4rem;
		border-radius: 999px;
	}
	.tag.org {
		background: var(--accent-soft);
		color: var(--accent-ink);
	}
	.tag.you {
		background: var(--line);
		color: var(--ink-soft);
	}
	.tag.seed {
		background: transparent;
		color: var(--ink-faint);
		border: 1px solid var(--line);
	}
	.tag.invited {
		background: transparent;
		color: var(--accent-ink);
		border: 1px solid var(--accent-soft);
	}
	.invite-form {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}
	.invite-form input {
		min-width: 0;
		padding: 0.55rem 0.7rem;
		border: 1px solid var(--line);
		border-radius: 8px;
		font: inherit;
	}
	.invite-form .btn {
		justify-content: center;
	}
	.hint {
		font-size: 0.82rem;
		margin-top: 0.6rem;
	}
	.link-btn {
		background: none;
		border: none;
		color: var(--ink-faint);
		font-size: 0.82rem;
		cursor: pointer;
		padding: 0.2rem 0.3rem;
	}
	.link-btn:hover {
		color: var(--danger-ink, #a12b21);
	}
</style>

// apps/web/src/pages/People.tsx
import { useState } from 'react';
import { api, ApiError } from '../api';
import { useApi } from '../useApi';
import { useTrip } from './TripShell';

type Person = {
	id: string;
	name: string;
	email: string;
	role: string;
	placeholder: boolean;
	seeded: boolean;
};

type Data = { me: string; organizer: boolean; people: Person[] };

export default function People() {
	const { trip, reloadTrip } = useTrip();
	const { data, error, reload } = useApi<Data>(`/trips/${trip.id}/people`);
	const [notice, setNotice] = useState<{ kind: 'ok' | 'error'; text: string } | null>(null);

	// The header shows the member avatars, so anything that changes the roster
	// has to refresh the shell too, not just this page.
	function refresh() {
		reload();
		reloadTrip();
	}

	if (!data) return error ? <p className="text-warn">{error}</p> : null;

	return (
		<>
			<div className="mb-5">
				<p className="muted m-0">Who is coming, and who still needs an invite.</p>
			</div>

			{notice && (
				<p
					role="status"
					className={[
						'mb-4 rounded-lg px-3.5 py-2.5 text-[0.9rem]',
						notice.kind === 'error'
							? 'bg-danger-soft text-danger-ink'
							: 'bg-accent-soft text-accent-ink'
					].join(' ')}
				>
					{notice.text}
				</p>
			)}

			<div
				className={
					data.organizer
						? 'grid grid-cols-[minmax(0,1fr)] items-start gap-5 lg:grid-cols-[minmax(0,1fr)_340px]'
						: 'grid grid-cols-[minmax(0,1fr)] gap-5'
				}
			>
				<section className="card px-5 py-5">
					<h3 className="mb-3.5 text-[1.05rem]">Members</h3>
					{/* Auto-fill columns rather than one long list: at 20 members a
					    single column is mostly empty space on a wide screen. */}
					<ul className="m-0 grid list-none grid-cols-[repeat(auto-fill,minmax(240px,1fr))] gap-x-6 gap-y-0.5 p-0">
						{data.people.map((p) => (
							<Row
								key={p.id}
								person={p}
								me={data.me}
								organizer={data.organizer}
								tripId={trip.id}
								onRemoved={refresh}
								onError={(text) => setNotice({ kind: 'error', text })}
							/>
						))}
					</ul>
				</section>

				{data.organizer && (
					<Invite
						tripId={trip.id}
						onDone={(text) => {
							setNotice({ kind: 'ok', text });
							refresh();
						}}
						onError={(text) => setNotice({ kind: 'error', text })}
					/>
				)}
			</div>
		</>
	);
}

function Row({
	person,
	me,
	organizer,
	tripId,
	onRemoved,
	onError
}: {
	person: Person;
	me: string;
	organizer: boolean;
	tripId: string;
	onRemoved: () => void;
	onError: (text: string) => void;
}) {
	const [busy, setBusy] = useState(false);

	async function remove() {
		setBusy(true);
		try {
			await api(`/trips/${tripId}/people/${person.id}`, { method: 'DELETE' });
			onRemoved();
		} catch (err) {
			onError(err instanceof ApiError ? err.message : 'Could not remove that member.');
			setBusy(false);
		}
	}

	const sub = person.placeholder
		? `${person.email} (not joined yet)`
		: person.seeded
			? 'Sample companion'
			: person.email;

	return (
		<li className="flex items-center gap-3 rounded-sm p-2 hover:bg-surface-2">
			<span className="grid size-[34px] shrink-0 place-items-center rounded-full bg-accent-soft font-semibold text-accent-ink">
				{person.name[0]}
			</span>
			<span className="flex min-w-0 flex-1 flex-col">
				<span className="flex min-w-0 items-center gap-1.5 font-medium">
					<span className="truncate" title={person.name}>
						{person.name}
					</span>
					{person.id === me && <Tag kind="you">you</Tag>}
					{person.role === 'organizer' && <Tag kind="org">organizer</Tag>}
					{person.placeholder ? (
						<Tag kind="invited">invited</Tag>
					) : (
						person.seeded && <Tag kind="seed">sample</Tag>
					)}
				</span>
				<span className="muted truncate text-[0.82rem]">{sub}</span>
			</span>
			{organizer && person.role !== 'organizer' && (
				<button
					type="button"
					disabled={busy}
					onClick={remove}
					aria-label={`Remove ${person.name}`}
					className="cursor-pointer border-none bg-transparent px-1 py-0.5 text-[0.82rem] text-ink-faint hover:text-danger-ink disabled:cursor-default"
				>
					Remove
				</button>
			)}
		</li>
	);
}

function Tag({ kind, children }: { kind: 'you' | 'org' | 'seed' | 'invited'; children: string }) {
	const style = {
		org: 'bg-accent-soft text-accent-ink',
		you: 'bg-line text-ink-soft',
		seed: 'border border-line text-ink-faint',
		invited: 'border border-accent-soft text-accent-ink'
	}[kind];
	return (
		<span
			className={`shrink-0 rounded-full px-1.5 py-px text-[0.68rem] font-semibold tracking-wider uppercase ${style}`}
		>
			{children}
		</span>
	);
}

function Invite({
	tripId,
	onDone,
	onError
}: {
	tripId: string;
	onDone: (text: string) => void;
	onError: (text: string) => void;
}) {
	const [email, setEmail] = useState('');
	const [busy, setBusy] = useState(false);

	async function submit(e: React.FormEvent) {
		e.preventDefault();
		setBusy(true);
		try {
			const { message } = await api<{ message: string }>(`/trips/${tripId}/people/invites`, {
				method: 'POST',
				body: { email }
			});
			setEmail('');
			onDone(message);
		} catch (err) {
			onError(err instanceof ApiError ? err.message : 'Could not send that invite.');
		}
		setBusy(false);
	}

	return (
		<section className="card sticky top-4 px-5 py-5">
			<h3 className="mb-3.5 text-[1.05rem]">Invite someone</h3>
			<form className="flex flex-col gap-2" onSubmit={submit}>
				<label className="flex flex-col gap-1.5 text-[0.82rem] font-medium text-ink-soft">
					Email address
					<input
						type="email"
						required
						autoComplete="off"
						value={email}
						onChange={(e) => setEmail(e.target.value)}
						className="min-w-0 rounded-lg border border-line bg-surface px-2.5 py-2 font-normal text-ink outline-none focus:border-accent"
					/>
				</label>
				<button className="btn primary justify-center" type="submit" disabled={busy}>
					{busy ? 'Sending...' : 'Send invite'}
				</button>
			</form>
			<p className="muted mt-2.5 text-[0.82rem]">
				If they already have an account they join right away. Otherwise they appear as a placeholder
				and take over the spot (and any expenses assigned to them) when they register with this
				email.
			</p>
		</section>
	);
}
